import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './components/header'
import Footer from './components/footer'
import web3 from 'web3'
import { useState } from 'react'


export default function Home() {

  const [web3, setWeb3] = useState()
  const [cuentas, setCuentas] = useState()


  return (
    <div>
      <Head>
        <title>Lotthereum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header cuentas={cuentas} setWeb3={setWeb3} setCuentas={setCuentas}/>
      <main className={styles.main}>
        <section className={styles.content}>
          <section className={styles.botonessm}>
            <section className={styles.btn1}>
              <p>Compra un boleto por 0.01 Ether</p>
              <button>Jugar</button>
            </section>
            <section className={styles.btn2}>
              <p>Admin Only: Selecciona un ganador</p>
              <button>Elegir Ganador</button>
            </section>
            <section className={styles.btn3}>
              <p>Admin Only: Pagar al ganador</p>
              <button>Pagar</button>
            </section>
          </section>
          <section className={styles.infosm}>
            <section className={styles.infolotto}>
              <div>
                <h4>Historial de loterias</h4>
              </div>
              <section>
                <p>Ganador #1</p>
                <p>0xf5gdfsdfa83saka</p>
              </section>
            </section>
            <section className={styles.infoplayers}>
              <div>
                <h4>Jugadores (1)</h4>
              </div>
              <section>
                <p>0xf5gdfsdfa83saka</p>
              </section>
            </section>
            <section className={styles.infobote}>
              <div>
                <h4>Bote</h4>
              </div>
              <section>
                <p>5 Ether</p>
              </section>
            </section>
          </section>
        </section>
      </main>
      <Footer/>
    </div>
  )
}
